image:
  file: .gitpod.dockerfile
ports:
    - port: 3000
      onOpen: open-preview
tasks:
    - init: >
        cp .env.example .env;
        pipenv install;
      command: pipenv run start;
    - command: echo "Welcome!"
