image:
  file: .gitpod.dockerfile
ports:
    - port: 3000
tasks:
    - init: >
        cat > .env2 <<- "EOF"
        DB_CONNECTION_STRING=sqlite:////tmp/database.db
        FLASK_APP=src/main.py
        FLASK_ENV=development
        EOF;
        pipenv install;

      command: >
        pipenv run start;
