image:
  file: .gitpod.dockerfile
ports:
    - port: 3000
      onOpen: open-preview
tasks:
    - init: >
        echo "DB_CONNECTION_STRING=sqlite:////database.db
        FLASK_APP=src/main.py
        FLASK_ENV=development" >> .env;
        pipenv install;
      command: pipenv run start;
    - command: echo "Welcome!"
